var eoy = [
  {"country": "United States", "eoyDonations": "6,292"},
  {"country": "Canada ", "eoyDonations": "633"},
  {"country": "Australia", "eoyDonations": "587"},
  {"country": "United Kingdom ", "eoyDonations": "515"},
  {"country": "India", "eoyDonations": "116"},
  {"country": "Germany", "eoyDonations": "108"},
  {"country": "New Zealand", "eoyDonations": "72"},
  {"country": "France ", "eoyDonations": "61"},
  {"country": "Netherlands", "eoyDonations": "54"},
  {"country": "Switzerland", "eoyDonations": "43"},
  {"country": "Italy", "eoyDonations": "41"},
  {"country": "Indonesia", "eoyDonations": "35"},
  {"country": "Brazil ", "eoyDonations": "33"},
  {"country": "Ireland", "eoyDonations": "33"},
  {"country": "Denmark", "eoyDonations": "33"},
  {"country": "Israel ", "eoyDonations": "31"},
  {"country": "Mexico ", "eoyDonations": "31"},
  {"country": "Sweden ", "eoyDonations": "31"},
  {"country": "Belgium", "eoyDonations": "30"},
  {"country": "Thailand ", "eoyDonations": "29"},
  {"country": "Romania", "eoyDonations": "29"},
  {"country": "Norway ", "eoyDonations": "28"},
  {"country": "Spain", "eoyDonations": "26"},
  {"country": "Greece ", "eoyDonations": "25"},
  {"country": "Russia ", "eoyDonations": "23"},
  {"country": "Malaysia ", "eoyDonations": "22"},
  {"country": "Singapore", "eoyDonations": "22"},
  {"country": "United Arab Emirates ", "eoyDonations": "20"},
  {"country": "South Africa ", "eoyDonations": "19"},
  {"country": "Finland", "eoyDonations": "18"},
  {"country": "Croatia", "eoyDonations": "17"},
  {"country": "Puerto Rico", "eoyDonations": "17"},
  {"country": "Czech Republic ", "eoyDonations": "17"},
  {"country": "Hong Kong", "eoyDonations": "16"},
  {"country": "Bulgaria ", "eoyDonations": "14"},
  {"country": "Austria", "eoyDonations": "11"},
  {"country": "Turkey ", "eoyDonations": "10"},
  {"country": "(not set)", "eoyDonations": "10"},
  {"country": "Latvia ", "eoyDonations": "9"},
  {"country": "Philippines", "eoyDonations": "9"},
  {"country": "Portugal ", "eoyDonations": "9"},
  {"country": "Japan", "eoyDonations": "9"},
  {"country": "Vietnam", "eoyDonations": "9"},
  {"country": "South Korea", "eoyDonations": "8"},
  {"country": "Poland ", "eoyDonations": "8"},
  {"country": "Slovenia ", "eoyDonations": "8"},
  {"country": "Hungary", "eoyDonations": "7"},
  {"country": "Saudi Arabia ", "eoyDonations": "7"},
  {"country": "Cyprus ", "eoyDonations": "7"},
  {"country": "Argentina", "eoyDonations": "6"}
];

module.exports = {
  eoy: eoy
};
