var eoy = [
  {"country": "United States", "eoyDonations": "6,292"},
  {"country": "Canada ", "eoyDonations": "633"},
  {"country": "Australia", "eoyDonations": "587"},
  {"country": "United Kingdom ", "eoyDonations": "515"},
  {"country": "India", "eoyDonations": "116"},
  {"country": "Germany", "eoyDonations": "108"},
  {"country": "New Zealand", "eoyDonations": "72"},
  {"country": "France ", "eoyDonations": "61"},
  {"country": "Netherlands", "eoyDonations": "54"},
  {"country": "Switzerland", "eoyDonations": "43"},
  {"country": "Italy", "eoyDonations": "41"},
  {"country": "Indonesia", "eoyDonations": "35"},
  {"country": "Brazil ", "eoyDonations": "33"},
  {"country": "Ireland", "eoyDonations": "33"},
  {"country": "Denmark", "eoyDonations": "33"},
  {"country": "Israel ", "eoyDonations": "31"},
  {"country": "Mexico ", "eoyDonations": "31"},
  {"country": "Sweden ", "eoyDonations": "31"},
  {"country": "Belgium", "eoyDonations": "30"},
  {"country": "Thailand ", "eoyDonations": "29"},
  {"country": "Romania", "eoyDonations": "29"},
  {"country": "Norway ", "eoyDonations": "28"},
  {"country": "Spain", "eoyDonations": "26"},
  {"country": "Greece ", "eoyDonations": "25"},
  {"country": "Russia ", "eoyDonations": "23"},
  {"country": "Malaysia ", "eoyDonations": "22"},
  {"country": "Singapore", "eoyDonations": "22"},
  {"country": "United Arab Emirates ", "eoyDonations": "20"},
  {"country": "South Africa ", "eoyDonations": "19"},
  {"country": "Finland", "eoyDonations": "18"},
  {"country": "Croatia", "eoyDonations": "17"},
  {"country": "Puerto Rico", "eoyDonations": "17"},
  {"country": "Czech Republic ", "eoyDonations": "17"},
  {"country": "Hong Kong", "eoyDonations": "16"},
  {"country": "Bulgaria ", "eoyDonations": "14"},
  {"country": "Austria", "eoyDonations": "11"},
  {"country": "Turkey ", "eoyDonations": "10"},
  {"country": "(not set)", "eoyDonations": "10"},
  {"country": "Latvia ", "eoyDonations": "9"},
  {"country": "Philippines", "eoyDonations": "9"},
  {"country": "Portugal ", "eoyDonations": "9"},
  {"country": "Japan", "eoyDonations": "9"},
  {"country": "Vietnam", "eoyDonations": "9"},
  {"country": "South Korea", "eoyDonations": "8"},
  {"country": "Poland ", "eoyDonations": "8"},
  {"country": "Slovenia ", "eoyDonations": "8"},
  {"country": "Hungary", "eoyDonations": "7"},
  {"country": "Saudi Arabia ", "eoyDonations": "7"},
  {"country": "Cyprus ", "eoyDonations": "7"},
  {"country": "Argentina", "eoyDonations": "6"}
];

var eoyLanguage2015OldForm = [
  { "language": "de", "eoyDonations": "17243" },
  { "language": "en-us", "eoyDonations": "1172" },
  { "language": "pt-br", "eoyDonations": "424" },
  { "language": "fr", "eoyDonations": "160" },
  { "language": "de-de", "eoyDonations": "124" },
  { "language": "en-gb", "eoyDonations": "115" },
  { "language": "it-it", "eoyDonations": "36" },
  { "language": "es-es", "eoyDonations": "34" },
  { "language": "en", "eoyDonations": "26" },
  { "language": "de-ch", "eoyDonations": "21" },
  { "language": "nl", "eoyDonations": "20" },
  { "language": "pt-pt", "eoyDonations": "15" },
  { "language": "ru-ru", "eoyDonations": "11" },
  { "language": "fr-fr", "eoyDonations": "9" },
  { "language": "ja", "eoyDonations": "9" },
  { "language": "es-mx", "eoyDonations": "8" },
  { "language": "de-at", "eoyDonations": "7" },
  { "language": "it", "eoyDonations": "7" },
  { "language": "es", "eoyDonations": "5" },
  { "language": "es-ar", "eoyDonations": "5" },
  { "language": "id", "eoyDonations": "5" },
  { "language": "pl", "eoyDonations": "5" },
  { "language": "da", "eoyDonations": "4" },
  { "language": "sv-se", "eoyDonations": "4" },
  { "language": "zh-cn", "eoyDonations": "4" },
  { "language": "en-au", "eoyDonations": "3" },
  { "language": "es-419", "eoyDonations": "3" },
  { "language": "fr-ca", "eoyDonations": "3" },
  { "language": "ru", "eoyDonations": "3" },
  { "language": "tr-tr", "eoyDonations": "3" }
];

module.exports = {
  eoy: eoy,
  eoyLanguage2015OldForm: eoyLanguage2015OldForm
};
